
export const LOGIN_USER ={
    REQUEST:"LOGIN_USER_REQUEST",
    SUCCESS:"LOGIN_USER_SUCCESS",
    ERROR:"LOGIN_USER_ERROR",
}

export const REGISTER_USER ={
    REQUEST:"REGISTER_USER_REQUEST",
    SUCCESS:"REGISTER_USER_SUCCESS",
    ERROR:"REGISTER_USER_ERROR",
}

export const CART ={
    ADD:"CART_ADD",
    INCREMENT:"CART_INCREMENT",
    DECREMENT:"CART_DECREMENT",
    REMOVE:"CART_REMOVE",
    CLEAR:"CART_CLEAR",
}

